on:
  push:
    branches:
    - master

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: hugo-deploy-gh-pages
      uses: linuxsuren/surenpi@master
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GITHUB_TOK }}
        HUGO_VERSION: "0.53"
        WEBSITE_GIT: "git@github.com:sanzharerdesov/poke.git"
        WEBSITE_DIR: "sanzharerdesov.github.io/poke"